import Head from 'next/head';
import { Component } from 'react';
import * as Tone from 'tone';
import { Piano } from '../piano/piano';

export default class Home extends Component<{}, { pressedNotes: string[] }> {
  sampler: Tone.Sampler;

  constructor(props) {
    super(props);

    this.state = {
      pressedNotes: [],
    };

    this.onNotePress = this.onNotePress.bind(this);
    this.onNoteRelease = this.onNoteRelease.bind(this);
  }

  initSampler() {
    if (!this.sampler) {
      this.sampler = new Tone.Sampler({
        urls: {
          C4: 'C4.mp3',
          'D#4': 'Ds4.mp3',
          'F#4': 'Fs4.mp3',
          A4: 'A4.mp3',
        },
        release: 1,
        baseUrl: 'https://tonejs.github.io/audio/salamander/',
      }).toDestination();
    }
  }

  onNotePress(e) {
    this.initSampler();

    const newPressedNotes = [...this.state.pressedNotes, e.detail.note];

    this.setState({
      pressedNotes: newPressedNotes,
    });

    Tone.loaded().then(() => {
      this.sampler.triggerAttackRelease(newPressedNotes, 4);
    });
  }

  onNoteRelease(e) {
    this.initSampler();

    const newPressedNotes = [...this.state.pressedNotes];
    newPressedNotes.splice(this.state.pressedNotes.indexOf(e.detail.note), 1);
    this.setState({
      pressedNotes: newPressedNotes,
    });

    Tone.loaded().then(() => {
      this.sampler.triggerRelease(newPressedNotes, 4);
    });
  }

  render() {
    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favico.png' />
        </Head>

        <div className='text-[1.5em]'>
          <Piano
            onNotePress={this.onNotePress}
            onNoteRelease={this.onNoteRelease}
            pressedNotes={this.state.pressedNotes}
          ></Piano>
        </div>
      </div>
    );
  }
}
